# Generated by Django 3.2.21 on 2023-09-12 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlignmentContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Alignment',
            },
        ),
        migrations.CreateModel(
            name='AttributeContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shortname', models.CharField(max_length=5)),
                ('full_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Attribute',
            },
        ),
        migrations.CreateModel(
            name='BackgroundContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('full_description', models.TextField()),
                ('feature', models.TextField()),
            ],
            options={
                'verbose_name': 'Background',
            },
        ),
        migrations.CreateModel(
            name='ClassContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('full_description', models.TextField()),
                ('features', models.TextField(default='I am blank')),
                ('saving_throw_1', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='SavingThrow1', to='charshare.attributecontenttable')),
                ('saving_throw_2', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='SavingThrow2', to='charshare.attributecontenttable')),
            ],
            options={
                'verbose_name': 'Class Choice',
            },
        ),
        migrations.CreateModel(
            name='InstrumentContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('full_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Musical Instrument',
            },
        ),
        migrations.CreateModel(
            name='LanguageContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('full_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Language',
            },
        ),
        migrations.CreateModel(
            name='RaceContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('full_description', models.TextField()),
                ('features', models.TextField(default='I am blank')),
            ],
            options={
                'verbose_name': 'Race',
            },
        ),
        migrations.CreateModel(
            name='SpellsContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('spell_level', models.IntegerField(choices=[(0, 'Cantrip'), (1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th')], default=0)),
                ('full_description', models.TextField()),
                ('spell_reqs', models.IntegerField(choices=[(0, ''), (1, 'Verbal'), (2, 'Somatic'), (3, 'Verbal and Somatic'), (4, 'Material'), (5, 'Verbal and Material'), (6, 'Somatic and Material'), (7, 'Verbal, Somatic and Material')], default=0)),
            ],
            options={
                'verbose_name': 'Spell',
            },
        ),
        migrations.CreateModel(
            name='ToolContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('full_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Tool',
            },
        ),
        migrations.CreateModel(
            name='SubRaceContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('full_description', models.TextField()),
                ('features', models.TextField(default='I am currently blank')),
                ('race', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='SubraceParentRace', to='charshare.racecontenttable')),
            ],
            options={
                'verbose_name': 'Subrace',
            },
        ),
        migrations.CreateModel(
            name='SubClassContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('full_description', models.TextField()),
                ('features', models.TextField(default='I am blank right now')),
                ('parent_class', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='SubclassParentClass', to='charshare.classcontenttable')),
            ],
            options={
                'verbose_name': 'Subclass Choice',
            },
        ),
        migrations.CreateModel(
            name='SkillsContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shortname', models.CharField(max_length=5)),
                ('full_description', models.TextField()),
                ('attribute', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='SkillsGoverningAttribute', to='charshare.attributecontenttable')),
            ],
            options={
                'verbose_name': 'Skill',
            },
        ),
        migrations.CreateModel(
            name='CharacterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=200)),
                ('inspiration', models.BooleanField(default=False)),
                ('faith', models.TextField(blank=True)),
                ('age', models.CharField(blank=True, max_length=24)),
                ('height', models.CharField(blank=True, max_length=24)),
                ('weight', models.CharField(blank=True, max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('backstory', models.TextField(blank=True)),
                ('allies', models.TextField(blank=True)),
                ('enemies', models.TextField(blank=True)),
                ('factions_and_orgs', models.TextField(blank=True)),
                ('hit_points', models.IntegerField(default=12)),
                ('armor_class', models.IntegerField(default=10)),
                ('alignment', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='CharacterAlignment', to='charshare.alignmentcontenttable')),
                ('background', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='CharacterBackground', to='charshare.backgroundcontenttable')),
                ('subrace', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='CharacterSubrace', to='charshare.subracecontenttable')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Character',
            },
        ),
        migrations.AddField(
            model_name='backgroundcontenttable',
            name='skill_proficiency_1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='BackgroundSkillGranted1', to='charshare.skillscontenttable'),
        ),
        migrations.AddField(
            model_name='backgroundcontenttable',
            name='skill_proficiency_2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='BackgroundSkillGranted2', to='charshare.skillscontenttable'),
        ),
    ]
