# Generated by Django 3.2.21 on 2023-09-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charshare', '0002_backgroundlanguageproficiencies_backgroundskillproficiencies_backgroundtoolproficiencies_characterat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcontenttable',
            name='features',
            field=models.TextField(default='No Features Entered'),
        ),
        migrations.AlterField(
            model_name='racecontenttable',
            name='features',
            field=models.TextField(default='No Features Entered'),
        ),
        migrations.AlterField(
            model_name='subclasscontenttable',
            name='features',
            field=models.TextField(default='No Features Entered'),
        ),
        migrations.AlterField(
            model_name='subracecontenttable',
            name='features',
            field=models.TextField(default='No Features Entered'),
        ),
    ]
