# Generated by Django 3.2.21 on 2023-09-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charshare', '0003_auto_20230914_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterdetails',
            name='attributes',
            field=models.ManyToManyField(through='charshare.CharacterAttributes', to='charshare.AttributeContentTable'),
        ),
    ]
