# Generated by Django 3.2.21 on 2023-09-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charshare', '0006_characterdetails_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterdetails',
            name='levels',
            field=models.ManyToManyField(to='charshare.CharacterLevels'),
        ),
        migrations.AddField(
            model_name='characterdetails',
            name='saving_throws',
            field=models.ManyToManyField(to='charshare.CharacterSavingThrows'),
        ),
        migrations.AddField(
            model_name='characterdetails',
            name='skills',
            field=models.ManyToManyField(to='charshare.CharacterSkillProficiencies'),
        ),
        migrations.AddField(
            model_name='characterdetails',
            name='spells',
            field=models.ManyToManyField(to='charshare.CharacterSpells'),
        ),
    ]
