# Generated by Django 3.2.21 on 2023-09-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charshare', '0007_auto_20230926_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterdetails',
            name='languages',
            field=models.ManyToManyField(to='charshare.CharacterLanguages'),
        ),
    ]
