# Generated by Django 3.2.21 on 2023-09-27 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charshare', '0008_characterdetails_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterdetails',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='charshare.CharacterAttributes'),
        ),
        migrations.AlterField(
            model_name='characterdetails',
            name='languages',
            field=models.ManyToManyField(blank=True, to='charshare.CharacterLanguages'),
        ),
        migrations.AlterField(
            model_name='characterdetails',
            name='levels',
            field=models.ManyToManyField(blank=True, to='charshare.CharacterLevels'),
        ),
        migrations.AlterField(
            model_name='characterdetails',
            name='saving_throws',
            field=models.ManyToManyField(blank=True, to='charshare.CharacterSavingThrows'),
        ),
        migrations.AlterField(
            model_name='characterdetails',
            name='skills',
            field=models.ManyToManyField(blank=True, to='charshare.CharacterSkillProficiencies'),
        ),
        migrations.AlterField(
            model_name='characterdetails',
            name='spells',
            field=models.ManyToManyField(blank=True, to='charshare.CharacterSpells'),
        ),
        migrations.CreateModel(
            name='CharacterSubclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubclassCharacter', to='charshare.characterdetails')),
                ('subclass', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='CharacterSubclass', to='charshare.subclasscontenttable')),
            ],
            options={
                'verbose_name': 'Character Subclass',
            },
        ),
        migrations.AddField(
            model_name='characterdetails',
            name='subclass',
            field=models.ManyToManyField(blank=True, to='charshare.CharacterSubclass'),
        ),
    ]
