# Generated by Django 3.2.21 on 2023-10-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charshare', '0009_auto_20230927_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundcontenttable',
            name='feature_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
