# Generated by Django 3.2.21 on 2023-10-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charshare', '0011_alter_characterdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterdetails',
            name='character_art',
            field=models.ImageField(default='https://res.cloudinary.com/dgyweielh/image/upload/v1698071582/stockchar_oquoft.jpg', upload_to='images'),
        ),
    ]
