# Generated by Django 3.2.21 on 2023-09-21 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charshare', '0004_characterdetails_attributes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterDetailSerializer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='charshare.alignmentcontenttable')),
                ('background', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='charshare.backgroundcontenttable')),
                ('subrace', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='charshare.subracecontenttable')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
