const CharModel = {
  user: "",
  character_name: "",
  subrace: 0,
  alignment: 0,
  background: 0,
  inspiration: false,
  faith: "",
  age: "",
  height: "",
  weight: "",
  notes: "",
  backstory: "",
  allies: "",
  enemies: "",
  factions_and_orgs: "",
  hit_points: 12,
  armor_class: 10,
  attributes: [],
  levels: [],
  skills: [],
  saving_throws: [],
  spells: [],
  languages: [],
  subclass: [],
};
